ofgwrite: fix build with musl libc
fix u_long and u_short

lib/libfec.c:628:5: error: unknown type name 'u_long'
628 |     u_long magic ;

fix missing rpmatch(line)

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>